export const ADD_INGREADEINT = 'ADD_INGREADEINT';
export const REMOVE_INGREADEINT = 'REMOVE_INGREADEINT';
export const CHANGE_BREAD_PROPETY = 'CHANGE_BREAD_PROPETY';
export const SET_INGREADEINTS = 'SET_INGREADEINTS';
export const SET_BREAD = 'SET_BREAD';
export const FETCH_INGREADIENTS_FAILED = 'FETCH_INGREADIENTS_FAILED';

export const PURCHASE_SANDWITCH_START = 'PURCHASE_SANDWITCH_START';
export const PURCHASE_SANDWITCH_SUCCES = 'PRUCHASE_BURGER_SUCCES';
export const PURCHASE_SANDWITCH_FAIL = 'PURCHASE_SANDWITCH_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const AUTH_START= 'AUTH_START';
export const AUTH_SUCCESS= 'AUTH_SUCCESS';
export const AUTH_FAIL= 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

