export const ADD_INGREADEINT = 'ADD_INGREADEINT';
export const REMOVE_INGREADEINT = 'REMOVE_INGREADEINT';
export const CHANGE_BREAD_PROPETY = 'CHANGE_BREAD_PROPETY';
export const SET_INGREADEINTS = 'SET_INGREADEINTS';
export const FETCH_INGREADIENTS_FAILED = 'FETCH_INGREADIENTS_FAILED';